import '@styles/globals.css'

import Header from '@components/Header';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import 'animate.css';
import Provider from '@components/Provider';


export const metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}


const RootLayout = ({ children }) => {
  return (
    <html lang="en">
        <body>
          <Provider>
            <div className='app'>
                <Header />
                {children}
            </div>
          </Provider>
        </body>
    </html>
  )
}

export default RootLayout